Return nil if savings_amount doesn't exist
This fixes a bug for @legal_aid_application.savings_amount.national_savings where it causes:

NoMethodError

undefined method `national_savings' for nil:NilClass